const objs = [
  {
    ano: 2019,
    tabela: [
      {
        posicao: 1,
        time: "Palmeiras",
        pontos: 80,
        jogos: 38,
        vitorias: 23,
        empates: 11,
        derrotas: 4,
        gols_pro: 63,
        gols_contra: 30,
        saldo_gols: 33,
      },
      {
        posicao: 2,
        time: "Santos",
        pontos: 74,
        jogos: 38,
        vitorias: 21,
        empates: 11,
        derrotas: 6,
        gols_pro: 55,
        gols_contra: 31,
        saldo_gols: 24,
      },
      {
        posicao: 3,
        time: "Flamengo",
        pontos: 71,
        jogos: 38,
        vitorias: 20,
        empates: 11,
        derrotas: 7,
        gols_pro: 59,
        gols_contra: 32,
        saldo_gols: 27,
      },
      {
        posicao: 4,
        time: "Grêmio",
        pontos: 65,
        jogos: 38,
        vitorias: 19,
        empates: 8,
        derrotas: 11,
        gols_pro: 46,
        gols_contra: 33,
        saldo_gols: 13,
      },
      {
        posicao: 5,
        time: "São Paulo",
        pontos: 64,
        jogos: 38,
        vitorias: 18,
        empates: 10,
        derrotas: 10,
        gols_pro: 42,
        gols_contra: 28,
        saldo_gols: 14,
      },

      {
        posicao: 20,
        time: "Havaí",
        pontos: 31,
        jogos: 38,
        vitorias: 7,
        empates: 10,
        derrotas: 21,
        gols_pro: 31,
        gols_contra: 61,
        saldo_gols: -30,
      },
    ],
  },
];

const jsonData = JSON.stringify(objs);

console.log(jsonData);
